name: Deploy NFC App

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Token
        run: |
          # Esto busca la palabra 'SECRET_TOKEN' en app.js y la cambia por tu secreto de GitHub
          sed -i "s/SECRET_TOKEN/${{ secrets.CUPRA_TOKEN }}/g" app.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
